### PR TITLE
Major UI Changes

### PR DESCRIPTION
**Pull request by rowhitswami**
### I added some features:

- [x] Changed "Blog" Button Style

- [x] Added hover and shadow effect in skill-items

- [x] Added Viewport Metatag

- [x] Added email icon

- [x] Removed background color of section title to give a flat view

- [x] Fixed view of resume section

Hope you like it :heart: 
Let me know if any problems occur in merging the PR.

### CODE REVIEW

**Comment by JasonHannanto** [comment]
Hey awesome work, a couple of changes I'd like to request:
1. Make the sections 100% width, as right now you can see the background on the sides, and I think that it detracts from the overall design.
2. Make the same animation CSS effect on the original button I had (the pink one). I like what you did for the blog button, however I think that the red box takes too much attention away and does not blend in well with the overall design. The animation hover effect is great however. I havent checked to see if doing the same hover effect on the button will be a lot of work, but if it it is then it is okay.

**Comment by rowhitswami** [comment]
Yes @JasonHannanto,  I reverted all the changes you asked. In addition, I also added some png files because, in the coming days, I'm thinking to convert your website into a Progressive Web App. The PWA (Progressive Web App) is kind of native Android app that can work without internet too. So be ready to blow your mind in coming days. :blush: 
You can read more about PWA here: https://developers.google.com/web/progressive-web-apps/

**Comment by JasonHannanto** [comment]
Hey @rowhitswami this is getting messy really fast. The changes you are implementing should not be part of this pull request, and should be part of a different development in itself. If it is easy for you, can you make this pull request with the changes only for the UI. So pretty much without the icons, code setup, etc. Also please remove the :hover for card-5 for now. Thanks!

**Comment by rowhitswami** [comment]
@JasonHannanto so what changes you want?
Please clearly mention :blush:

**Comment by JasonHannanto** [comment]
1. Remove anything related to WPA integration
2. Remove Hover on skill-card-5 [css]

**Comment by rowhitswami** [comment]
@JasonHannanto Please review the changes.

**Comment by JasonHannanto** [comment]
Awesome so far looks good, thanks a lot!

**Pull request merged**
